name:                pygen
version:             0.1.0.0
github:              "githubuser/snekServer"
license:             BSD3
author:              "Eduardo Hidalgo"
maintainer:          "eshidalgo97@gmail.com"
copyright:           "2019 Eduardo Hidalgo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/snekServer#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- random
- pretty
- aeson
- bytestring

library:
  source-dirs: src

executables:
  pygen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pygen

tests:
  pygen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pygen
